package me.xingz;

import java.io.*;
import java.net.URL;
import java.nio.channels.Channels;
import java.nio.channels.ReadableByteChannel;
import java.util.Arrays;


public class Test {

    public static void main(String[] args) {
        System.out.println(Double.valueOf("+24.95"));
        System.out.println(String.valueOf(Double.valueOf("+24.95")));
//        Arrays.binarySearch
        int test = (Integer.MAX_VALUE + 2) >>> 1;
        System.out.println(test);
//        String url = "http://download.finance.yahoo.com/d/quotes.csv?s=SINA+SOHU+NTES+BIDU+NCTY+KZ+JRJC+CTRP+JOBS+UTSI+CNTF+SMI+ACTS+EDU+VISN+AMCN+ACH+CEO+CYD+GSH+CHL+LFC+SORL+CHA+SNP+SHI+CEA+EFUT+HNP+ZNH+CSIQ+CBAK+CAAS+CHNR+NDAC+FFHL+NTE+DL+STV+XIN+ATV+SOL+TSL+YGE+CISG+HIMX+JASO+OIIM+SIMO+PTR+CHU+ASX+AUO+TSM+UMC+SPIL+GIGM+CYOU+HTHT+CHT+SYUT+CCGM+SFUN+DYNP+CCIH+NOAH+BITA+XNY+KNDI+CNET+ATAI+LIWA+YUII+HEAT+TXIC+JKS+RINO+DQ+CRTP+CHBT+HGSH+SEED+BEST+WATG+CCME+FUQI+GSOL+GURE+CAST+CADC+JFC+WUHN+FEED+CO+RCON+ABAT+HOLI+KONE+SPU+CIIC+CPHI+APWR+CREG+SINO+JGBO+CHNG+SCEI+CLNT+CHIO+CXDC+CELM+CJJD+CCM+SBAY+ALN+BSPM+CDII+CALI+SVA+CGA+VALV+NOEC+BORN+ONP+OSN+VNET+RENN+NQ+FENG+ZX+CNIT+VIPS+YY+DSWL+AAAE+APWC+IMOS+AACAY+ACGBY+AGVO+AHCHY+AICAF+AIDA+AIVI+AKRK+ALMMF+AMVGF+ANGGY+CMFO+AMCG+AMGY+HPJ+LEDS+ARTB+BACHY+BCAUY+BCHM+BCMXY+BDEV+BNSO+EVK+NEWN+CNR+EGT+BEER+BEIJF+BELLY+BFAR+BHKLY+BJCHF+BJINY+BKEAY+SGOC+CLWT+BOTRF+BOTX+BSDGY+BSHG+IDI+BYDDF+CABLF+CAGM+HIHO+KGJI+NFEC+MPEL+CAOVY+CARCY+CASDY+CBEH+CBGH+CBLUY+CBUMY+CBRAF+SSW+CCCGY+JMHLY+CBPO+XHFNF+HGHN+JPAK+HGKGY+KEYP+HHGM+KMSWF+HIGR+XNFHF+HIIDY+XNGSY+XSELY+XYIGF+HKAEY+YINGY+YIPCF+JADA+YYINE+KRYPY+ZHAOF+PPCCY+JELCY+HKXCF+PSGP+QING+KURU+RDBO+RNFU+RNHEF+JEXYF+SEXHF+KWHAY+JEXYY+SGHIY+JIXAY+SHALY+LEGE+SHANF+SHGXY+SHKLY+LKHLY+SHTDF+SHTGY+TRUHY+TSGTF+TSYHY+TTNDY+XNWU+LMPMY+LTUS+MAANF+MAORF+MLLUY+NANI+TVBCY+CEVIY+TXNM+NIVS+UOLI+CHME+NOBGF+CCCL+WGHGY+VTSYF+NWRLY+SLUXY+SLVA+SNAS+SNFRY+SNLAY+OPEI+UIBGF+WGLD+HKXCY+HLDCY+HLDVF+HLPPY+HMCTF+HNLGF+HNLGY+HOKCY+CHCC+HOWWY+CHCG+SRRY+CHDA+HQGE+STTFY+HRELF+SUHJY+CHDP+CHEUY+SWRAY+HRELY+SYUP+HSNGY+HSYT+SOUG+HTCMY+HUABF+HUIHY+HUIY+HYSNY+IDCBF+IDCBY+IDCX+IICN+IINHY+IKTSY+XYIGY+TSGTY+CHPN+CHPXY+CHWTF+CHHE+CHSY+CICHY+ZHDM+ZHEXF+CITAY+ZHYLF+CICOY+CIDHY+CHSTY+CIVN+CIFHY+CIHD+CIHKY+ZIJMF+CHOR+ZLIOY+ZTCOF+CHLBF+CIWT+ZYCI+TAAI+TCEHY+TCEPY+TCYMF+CKGT+CKUN+SHWGY+SHZNY+SIMTF+OROVY+TCTZF+TCYMY+SIELY+SIOLY+TRUHF+SWRBY+ORSX+PBEP+CHNC+PIAIF+PKSGY+KSTV+WOSSF+WSYS+WTFS+WUMSF+WWNTF+WYNMF+ZHEXY+ZIJMY+ZTCOY+WUMSY+WWNTY+WYNMY+MNOIY+NOBGY+CLPXY+CMAKY+CMNW+PNGAY+CNER+CPCAY+CPDV+CPKPF+CRHKY+CRHO+CRJI+CRUI+CHOLY+CHOLF+CRWOY+CSDXY+CSEHY+CSGH+CSGJ+CSKD+CCGY+CSNH+CSOL+CSRGY+CSUAY+CSWG+CSWYY+CTEK+CTHL+CTPCY+CTVZ+CPKPY+HUAZ+CCOZY+CCOZF+CDBH+CDBT+CDGXF+CDSG+AIRYY+BACHF+BCAUF+BKEAF+CICHF+BYDDY+DPNEY+DRCR+DUKS+DXIN+EAST+EESC+EKONY+ENHD+ESPGY+FEPU+FIRRY+FLMS+FPAFF+FXCNY+GGDVY+GHII+GIGNF+GIGNY+GMDTF+GOEG+GPHG+GTVI+GWLLY+GXYEF+GXYEY+GZPHY+GZUHY+HDVTY+HEGIF+HEGIY+FPAFY+CVPH+CWPWF+CWYCY+CYDI+CYHM+CYIG+DCRD+DFEL+DFIHY+DGDH+DGWIY+DION+DIPGY+DKSP+DNFGF+DNGH+DPNEF+DNFGY+LITB+PME+CCCR+WUBA+WBAI+ATHM+AMC+NVFY+WB+TEDU+LEJU+KANG+JD+TOUR+CMCM+GOAS+JMEI+ZPIN+XNET+BABA+SKYS+EHIC+MOMO+HLG+JP+YRD+BGNE+YIN+COE+JMU+GSUM+CLDC+ZTO+BSTI&f=snabcc1p2kjwj6k5t8";
//
//        try {
//            downloadUsingNIO(url, "/Users/xzhou/Developer/xing/quotes.csv");
//
//            downloadUsingStream(url, "/Users/xzhou/Developer/xing/quotes_1.csv");
//        } catch (IOException e) {
//            e.printStackTrace();
//        }


    }

//    private static void downloadUsingStream(String urlStr, String file) throws IOException{
//        URL url = new URL(urlStr);
//        BufferedInputStream bis = new BufferedInputStream(url.openStream());
//        FileOutputStream fis = new FileOutputStream(file);
//        byte[] buffer = new byte[1024];
//        int count=0;
//        while((count = bis.read(buffer,0,1024)) != -1)
//        {
//            fis.write(buffer, 0, count);
//        }
//        fis.close();
//        bis.close();
//    }
//
//    private static void downloadUsingNIO(String urlStr, String file) throws IOException {
//        URL url = new URL(urlStr);
//        ReadableByteChannel rbc = Channels.newChannel(url.openStream());
//        FileOutputStream fos = new FileOutputStream(file);
//        fos.getChannel().transferFrom(rbc, 0, Long.MAX_VALUE);
//        fos.close();
//        rbc.close();
//    }
}
